# Generated by Django 5.1.1 on 2024-10-16 10:44

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='Home_images/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=200, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('show_quote_form', models.BooleanField(default=True)),
                ('quote_form_title', models.CharField(blank=True, max_length=200, null=True)),
                ('quote_form_field1_title', models.CharField(blank=True, max_length=200, null=True)),
                ('quote_form_field1_placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('quote_form_field2_title', models.CharField(blank=True, max_length=200, null=True)),
                ('quote_form_field2_placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('quote_form_field3_title', models.CharField(blank=True, max_length=200, null=True)),
                ('quote_form_field3_placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('quote_form_button_text', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_language', to='lang.languages')),
            ],
        ),
        migrations.CreateModel(
            name='blogSectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(blank=True, max_length=200, null=True)),
                ('title_big', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_title_language', to='lang.languages')),
            ],
        ),
        migrations.CreateModel(
            name='clientSectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(blank=True, max_length=200, null=True)),
                ('title_big', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_title_language', to='lang.languages')),
            ],
        ),
        migrations.CreateModel(
            name='funFactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_count', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funfact_language', to='lang.languages')),
            ],
            options={
                'verbose_name_plural': '5. Fun Facts',
            },
        ),
        migrations.CreateModel(
            name='funFactSectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(blank=True, max_length=200, null=True)),
                ('title_big', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funfact_title_language', to='lang.languages')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_seo_language', to='lang.languages')),
            ],
        ),
        migrations.CreateModel(
            name='projectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_category_language', to='lang.languages')),
            ],
            options={
                'verbose_name_plural': '4. Project Categories',
            },
        ),
        migrations.CreateModel(
            name='projectSectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(blank=True, max_length=200, null=True)),
                ('title_big', models.CharField(blank=True, max_length=255, null=True)),
                ('all_work_text', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_title_language', to='lang.languages')),
            ],
        ),
        migrations.CreateModel(
            name='projectsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Home_images/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text', models.CharField(blank=True, max_length=200, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prject_category', to='homepage.projectcategory')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_language', to='lang.languages')),
            ],
            options={
                'verbose_name_plural': '3. Projects',
            },
        ),
        migrations.CreateModel(
            name='serviceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Home_images/')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=220, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_language', to='lang.languages')),
            ],
            options={
                'verbose_name_plural': '2. Services',
            },
        ),
        migrations.CreateModel(
            name='serviceSectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(blank=True, max_length=200, null=True)),
                ('title_big', models.CharField(blank=True, max_length=255, null=True)),
                ('service_card_more_text', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_title_language', to='lang.languages')),
            ],
        ),
        migrations.CreateModel(
            name='testimonialSectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(blank=True, max_length=200, null=True)),
                ('title_big', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_title_language', to='lang.languages')),
            ],
        ),
        migrations.CreateModel(
            name='testimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_language', to='lang.languages')),
            ],
            options={
                'verbose_name_plural': '6. Testimonials',
            },
        ),
    ]
