# Generated by Django 5.1.1 on 2024-10-16 10:44

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_seo_language', to='lang.languages')),
            ],
        ),
        migrations.CreateModel(
            name='aboutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_white', models.CharField(blank=True, max_length=200, null=True)),
                ('title_red', models.CharField(blank=True, max_length=200, null=True)),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('count_title1', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('count_title2', models.CharField(blank=True, max_length=255, null=True)),
                ('project_delivered', models.IntegerField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=255, null=True)),
                ('button_url', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_language', to='lang.languages')),
            ],
            options={
                'verbose_name_plural': '1. About Page Intro',
            },
        ),
        migrations.CreateModel(
            name='clientsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('company_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='clients/')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_language', to='lang.languages')),
            ],
            options={
                'verbose_name_plural': '3. Clients',
            },
        ),
        migrations.CreateModel(
            name='teamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, default='https://www.facebook.com', max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, default='https://twitter.com', max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, default='https://www.linkedin.com', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_language', to='lang.languages')),
            ],
            options={
                'verbose_name_plural': '2. Team Members',
            },
        ),
        migrations.CreateModel(
            name='teamSectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(blank=True, max_length=200, null=True)),
                ('title_big', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_title_language', to='lang.languages')),
            ],
        ),
    ]
