# Generated by Django 5.1.1 on 2024-10-16 10:44

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=500)),
                ('phone', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='contact_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribe_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box1_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('box1_title', models.CharField(blank=True, max_length=250, null=True)),
                ('box1_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('box2_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('box2_title', models.CharField(blank=True, max_length=250, null=True)),
                ('box2_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('box3_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('box3_title', models.CharField(blank=True, max_length=250, null=True)),
                ('box3_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('iframe_title', models.CharField(blank=True, max_length=200, null=True)),
                ('map_iframe', models.TextField(blank=True, null=True)),
                ('form_title', models.CharField(blank=True, max_length=200, null=True)),
                ('name_field_label', models.CharField(blank=True, max_length=200, null=True)),
                ('name_field_placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('email_field_label', models.CharField(blank=True, max_length=200, null=True)),
                ('email_field_placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_field_label', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_field_placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('message_field_label', models.CharField(blank=True, max_length=200, null=True)),
                ('message_field_placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_field_label', models.CharField(blank=True, max_length=200, null=True)),
                ('submit_button_text', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info_language', to='lang.languages')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_page_seo_language', to='lang.languages')),
            ],
        ),
    ]
