# Generated by Django 5.1.1 on 2024-10-16 10:44

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_expense', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('rent/mortgage', 'Rent/Mortgage'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('food_and_dining', 'Food and Dining'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('debt_payments', 'Debt Payments'), ('healthcare_and_medical_expenses', 'Healthcare and Medical Expenses'), ('miscellaneous_expenses', 'Miscellaneous Expenses'), ('personal_care', 'Personal Care'), ('fees', 'Fees'), ('others', 'Others')], max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='itemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyPaymentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('total_payment', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='crmProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('progress', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
                ('project_type', models.CharField(choices=[('client_project', 'Client Project'), ('internal_project', 'Internal Project')], default='client_project', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('price', models.IntegerField()),
                ('label', models.CharField(blank=True, choices=[('started', 'Started'), ('completed', 'Completed'), ('new_customer', 'New Customer'), ('important', 'Important'), ('closed', 'Closed'), ('running', 'Running'), ('canceled', 'Canceled'), ('pending', 'Pending')], max_length=50, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.guser')),
                ('team', models.ManyToManyField(blank=True, related_name='project_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='crmTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('done', 'Done')], default='to_do', max_length=50)),
                ('priority', models.CharField(blank=True, choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical'), ('blocker', 'Blocker')], max_length=50, null=True)),
                ('label', models.CharField(blank=True, choices=[('started', 'Started'), ('completed', 'Completed'), ('new_customer', 'New Customer'), ('important', 'Important'), ('closed', 'Closed'), ('running', 'Running'), ('canceled', 'Canceled'), ('pending', 'Pending')], max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='task_team', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crmprojects')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('billDate', models.DateField(blank=True, null=True)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('PARTIALLY_PAID', 'PARTIALLY PAID'), ('PAID', 'PAID')], default='UNPAID', max_length=100)),
                ('discount_amount', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('other_fees_name', models.CharField(blank=True, default='Other Fees', max_length=255, null=True)),
                ('other_fees_amount', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, default='This is a computer generated invoice no need signature', null=True)),
                ('sub_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.guser')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.crmprojects')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Product_Images/')),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('unit_type', models.CharField(max_length=100)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('fake_sales', models.IntegerField(blank=True, null=True)),
                ('fake_stars', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.FloatField(default=0.0)),
                ('sub_total', models.FloatField(default=0.0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.items')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='invoice_related_items', to='crm.items'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_ammount', models.FloatField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_note', models.TextField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='project_files/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crmprojects')),
            ],
        ),
    ]
